apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbols-db
spec:
  replicas: 1
  selector:
    matchLabels:
      application: symbols
      type: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: symbols
        type: db
    spec:
      containers:
        - name: db
          image: mongo:4.2
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data-volume
      volumes:
        - name: mongo-data-volume
          emptyDir: {}
