apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: symbols-api
spec:
  replicas: 2
  selector:
    matchLabels:
      application: symbols
      type: api
  template:
    metadata:
      labels:
        application: symbols
        type: api
    spec:
      containers:
        - name: api
          image: lfyuomrgylo/symbols-api
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: symbols-db
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health

